apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: vm-exporter2
    app.kubernetes.io/version: v2.0.0-3
  name: vm-exporter2
  namespace: default
spec:
  endpoints:
  - interval: 15s
    port: vmhttp2
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_controller_name
      targetLabel: name
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: vm-exporter2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vm-exporter2
    app.kubernetes.io/version: v2.0.0-3
  name: vm-exporter2
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: vmhttp2
    port: 9226
    targetPort: 9226
  selector:
    kubevirt.io: virt-launcher
